---
title: "A seasonal ARIMA model to predict monthly average temperatures in Victoria, BC"
author: "Viet Dao"
date: "May 2021"
output: 
  html_document:
    number_sections: true
---

```{r, results='hide', message=FALSE, warning=FALSE}
library(readr)
# import the data, NAs already filled
vicTemp <- read_csv("data/victemp.csv")
```

# Graphing the data
```{r fig.align="center"}
library(astsa)
# create time series, graph it
vicTemp <- ts(vicTemp$TAVG, start=c(1992,12), end=c(2021,2), frequency = 12) 
plot.ts(vicTemp, ylab = 'Celcius', main = 'Figure 1. Average monthly air temperatures in Victoria') # Fig1
```

# Transformation
```{r fig.align="center"}
# transform the series (take the first difference and first seasonal difference)
tsplot(diff(diff(vicTemp),12), main = "Figure 2. Transformed series", 
       ylab = "Celcius")  # Fig2
abline(h=0, col=2)
```

# Fitted Model
```{r}
acf2(diff(diff(vicTemp),12), 100, main = "Figure 3. ACF and PACF of transformed series") # Fig3
```

We identify d = 1, P = 0, D = 1, Q = 1, s = 12 from the transformation, ACF, and PACF plots. However, it is not clear what p and q are so we try many values for them in the fitted models and examine the residual analysis, which results in the final model (with p=q=1).

```{r}
# p = 1, d = 1, q = 1, P = 0,  D = 1, Q = 1, s = 12
sarima(vicTemp, 1,1,1, 0,1,1, 12) # Fig4
```

# Predictions
```{r fig.align="center"}
fore <- sarima.for(vicTemp,10, 1,1,1, 0,1,1, 12) #Fig5 & Table1
title(main="Figure 5. Predictions from March 2021 to December 2021", 
      ylab="                            (Celcius)")
```

```{r}
library(kableExtra)
months <- c('03/2021', '04/2021', '05/2021', '06/2021', '07/2021', '08/2021', '09/2021', '10/2021', '11/2021', '12/2021')
d <- data.frame("Months" = months, "Predictions" = fore$pred, "Lower Bound" = fore$pred - 1.96*fore$se, "Upper Bound" = fore$pred - 1.96*fore$se)
d %>%
  kbl() %>%
  kable_material(c("striped", "hover")) %>%
  footnote(general_title = "", general = "Table 1. Predicted average temperatures for the next 10 monhts.") #Table1
```